name: drm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - graphviz
    - hnswlib
    - matplotlib
    - networkx
    - neo4j
    - notebook
    - ipykernel
    - ipywidgets
    - sphinx
    - sphinx-rtd-theme
    - nbsphinx
    - tqdm
    - traitlets
    - rdflib